name: club_hub
description: Gestor de entidades deportivas - Flutter + Firebase (stack low-cost)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Estado y navegaciÃ³n
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.1.3

  # Persistencia simple para el color de marca
  shared_preferences: ^2.3.2

  # Utilidades
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
